# ── Desarrollo local (HTTP puro, sin SSL) ────────────
server {
    listen 80;
    server_name localhost;

    # /api/ → API Node.js en puerto 4000
    location /api/ {
        #proxy_pass         http://api_backend/;
        #proxy_pass         http://api:4000/;
        proxy_pass         http://api:4000;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # / → Vite dev server (con soporte WebSocket para HMR)
    location / {
        #proxy_pass         http://web_frontend;
        proxy_pass         http://web:5173; 
        proxy_http_version 1.1;
        # Estos dos headers son necesarios para el WebSocket de Vite (hot-reload)xxss
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
    }

    location /health {
        #proxy_pass http://api_backend/health;
        proxy_pass http://api:4000/health;
        access_log off;
    }
}